<?php
$link = mysqli_connect("localhost", "root", "", "mechanicly");

// Check connection

if($link === false){

    die("ERROR: Could not connect. " . mysqli_connect_error());

}



 $array = json_decode('{
            "model_id": "7200004",
            "model": "100",
            "subbody": "",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200004&country-code=us"
        }, {
            "model_id": "7200005",
            "model": "200\/quattro",
            "subbody": "",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200005&country-code=us"
        }, {
            "model_id": "7200006",
            "model": "4000",
            "subbody": "",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200006&country-code=us"
        }, {
            "model_id": "7200008",
            "model": "5000",
            "subbody": "",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200008&country-code=us"
        }, {
            "model_id": "7200001",
            "model": "80",
            "subbody": "",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200001&country-code=us"
        }, {
            "model_id": "7200003",
            "model": "90\/quattro",
            "subbody": "",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200003&country-code=us"
        }, {
            "model_id": "7200009",
            "model": "A3\/quattro",
            "subbody": "",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200009&country-code=us"
        }, {
            "model_id": "7200002",
            "model": "A4 Avant",
            "subbody": "(09-)",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200002&country-code=us"
        }, {
            "model_id": "7200010",
            "model": "A4 Cabriolet",
            "subbody": "",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200010&country-code=us"
        }, {
            "model_id": "7200011",
            "model": "A4 Cabriolet",
            "subbody": "(09-)",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200011&country-code=us"
        }, {
            "model_id": "7200012",
            "model": "A4\/quattro",
            "subbody": "(96-01)",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200012&country-code=us"
        }, {
            "model_id": "7200013",
            "model": "A4\/quattro",
            "subbody": "(02-)",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200013&country-code=us"
        }, {
            "model_id": "7200014",
            "model": "A4\/quattro",
            "subbody": "(09-)",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200014&country-code=us"
        }, {
            "model_id": "7200015",
            "model": "A5\/quattro",
            "subbody": "",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200015&country-code=us"
        }, {
            "model_id": "7200016",
            "model": "A6\/quattro",
            "subbody": "(94-97)",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200016&country-code=us"
        }, {
            "model_id": "7200017",
            "model": "A6\/quattro",
            "subbody": "(98-04)",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200017&country-code=us"
        }, {
            "model_id": "7200018",
            "model": "A6\/quattro",
            "subbody": "(05-)",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200018&country-code=us"
        }, {
            "model_id": "7200019",
            "model": "A6\/quattro",
            "subbody": "(09-)",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200019&country-code=us"
        }, {
            "model_id": "7200039",
            "model": "A7\/quattro",
            "subbody": "",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200039&country-code=us"
        }, {
            "model_id": "7200020",
            "model": "A8\/quattro",
            "subbody": "(97-03)",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200020&country-code=us"
        }, {
            "model_id": "7200021",
            "model": "A8\/quattro",
            "subbody": "(04-)",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200021&country-code=us"
        }, {
            "model_id": "7200022",
            "model": "A8\/quattro",
            "subbody": "(07-)",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200022&country-code=us"
        }, {
            "model_id": "7200023",
            "model": "A8\/quattro",
            "subbody": "(10-)",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200023&country-code=us"
        }, {
            "model_id": "7200024",
            "model": "allroad",
            "subbody": "",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200024&country-code=us"
        }, {
            "model_id": "7200025",
            "model": "Cabriolet",
            "subbody": "",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200025&country-code=us"
        }, {
            "model_id": "7200026",
            "model": "Coupe\/quattro",
            "subbody": "",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200026&country-code=us"
        }, {
            "model_id": "7200045",
            "model": "Q3",
            "subbody": "",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200045&country-code=us"
        }, {
            "model_id": "7200027",
            "model": "Q5",
            "subbody": "",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200027&country-code=us"
        }, {
            "model_id": "7200028",
            "model": "Q7",
            "subbody": "",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200028&country-code=us"
        }, {
            "model_id": "7200029",
            "model": "R8",
            "subbody": "",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200029&country-code=us"
        }, {
            "model_id": "7200030",
            "model": "RS4",
            "subbody": "",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200030&country-code=us"
        }, {
            "model_id": "7200041",
            "model": "RS5",
            "subbody": "",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200041&country-code=us"
        }, {
            "model_id": "7200031",
            "model": "RS6",
            "subbody": "",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200031&country-code=us"
        }, {
            "model_id": "7200043",
            "model": "RS7",
            "subbody": "",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200043&country-code=us"
        }, {
            "model_id": "7200046",
            "model": "S3",
            "subbody": "",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200046&country-code=us"
        }, {
            "model_id": "7200032",
            "model": "S4",
            "subbody": "",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200032&country-code=us"
        }, {
            "model_id": "7200034",
            "model": "S5",
            "subbody": "",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200034&country-code=us"
        }, {
            "model_id": "7200035",
            "model": "S6",
            "subbody": "",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200035&country-code=us"
        }, {
            "model_id": "7200040",
            "model": "S7",
            "subbody": "",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200040&country-code=us"
        }, {
            "model_id": "7200036",
            "model": "S8",
            "subbody": "",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200036&country-code=us"
        }, {
            "model_id": "7200044",
            "model": "SQ5",
            "subbody": "",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200044&country-code=us"
        }, {
            "model_id": "7200037",
            "model": "TT",
            "subbody": "",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200037&country-code=us"
        }, {
            "model_id": "7200038",
            "model": "V8",
            "subbody": "",
            "href": "\/v1\/vehicles?manufacturer_id=AUD0&model_id=7200038&country-code=us"
        }', true);


 ?>
vehicle_table_id = 52